### ISSUE TITLE
Option to provide a class to the wrapping span

### ISSUE THREAD

**Issue by bompi88** [gwendall/meteor-tapi18n-react#4]
I suggest to add an attribute `className` to the React class, `className`, that adds the corresponding css classes to the span wrapping the returned text. You can then do like this:

``` html
<TAP className="title-text" label="index.title" />
```

which should render something like:

``` html
<span class="title-text">My awesome title</span>
```

Without this, you may have to write unwanted css rules like:

``` css
.title-text span {
  color: #fff;
  ...
}
```

when you actually wants something like:

``` css
.title-text {
  color: #fff;
  ...
}
```
